### ISSUE TITLE
Upgrade to rabbitmq 3.8.x

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/docker#10]
Rabbitmq 3.7 is "End of General Support" since 31 March 2020.

Please consider upgrading to RabbitMQ 3.8.x.

-  https://www.rabbitmq.com/versions.html
- https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.25

**Comment by rhaist** [comment]
I am using `3.8-management` in production.
Seems safe to upgrade for me.

**Comment by SamuelHassine** [comment]
Thanks! Done.
