### ISSUE TITLE
client_secret missing for GoogleStrategy

### ISSUE THREAD

**Issue by ideologysec** [OpenCTI-Platform/docker#12]
- configuring/deploying via docker-compose
- for purposes of testing, using the docker-compose.yml file on a local machine via docker
- attempting to configure GoogleStrategy plugin via docker-compose.yml:

```
- PROVIDERS__GOOGLE__STRATEGY=GoogleStrategy
- PROVIDERS__GOOGLE__CONFIG__CLIENT__ID=${GOOGLE_CLIENT_ID}
- PROVIDERS__GOOGLE__CONFIG__CLIENT__SECRET=${GOOGLE_CLIENT_SECRET}
- PROVIDERS__GOOGLE__CONFIG__CALLBACK_URL=${GOOGLE_CALLBACK_URL}
- PROVIDERS__LOCAL__STRATEGY=LocalStrategy
```

- set these via .env file for testing
- tried the strings with and without quotes

- ERROR! "client_secret missing"

**Comment by SamuelHassine** [comment]
Hello @ideologysec,

As mentioned [in the documentation](https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a#c3cb32099f69486882015bcac9bb2b0c) levels of configuration are represented by double underscores. But the `client_id`, `client_secret`, etc. are just config keys with a sigle underscore.

In your case, the correct configuration is:

```
- PROVIDERS__GOOGLE__STRATEGY=GoogleStrategy
- PROVIDERS__GOOGLE__CONFIG__CLIENT_ID=${GOOGLE_CLIENT_ID}
- PROVIDERS__GOOGLE__CONFIG__CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
- PROVIDERS__GOOGLE__CONFIG__CALLBACK_URL=${GOOGLE_CALLBACK_URL}
- PROVIDERS__LOCAL__STRATEGY=LocalStrategy
```

**Comment by ideologysec** [comment]
I apologize, I had a comment typed up indicating I had figured this out, and was ready to hit close and comment... and it apparently never went through. Thanks for the doc link. I'm sorted out!
