### ISSUE TITLE
Minio Invalid Credentials Error

### ISSUE THREAD

**Issue by ccombs-sqsp** [OpenCTI-Platform/docker#15]
I have a strange error where the successful running of openCTI depends on where the directory is cloned.

In the original project folder where I cloned it, I ran the following commands:

```
git clone https://github.com/OpenCTI-Platform/docker.git
cd docker
cp .env.example .env
docker-compose --compatibility up
```

And got the following error from minio_1:

`ERROR Unable to initialize server switching into safe-mode: Unable to initialize sub-systems: Unable to initialize config system: Invalid credentials`

However, when I changed folders where I clone the repo, it runs fine. My hunch is that there must be some environment configuration that's messing up my first clone but I don't know what/where it is.

**Comment by SamuelHassine** [comment]
Hello @ccombs-sqsp,

Sorry we did not see your issue.I think you should just change your Minio access/secret key. I'm closing this issue for now. Please let me know if you have any trouble.

Kind regards,
Samuel
