### ISSUE TITLE
Upgrading from 3.3.2 to 4.1.2

### ISSUE THREAD

**Issue by marcosepp** [OpenCTI-Platform/docker#21]
Hi!

Looks like newer version doesn't use Graken anymore. I've upgraded CTI to 4.1.2 and all my data is lost. I believe it's still in Graken but I can't find anywhere how to migrate the data...

**Comment by SamuelHassine** [comment]
Hello @marcosepp,

Unfortunately, the migration between OpenCTI 3.3.X and OpenCTI 4.X.X is not transparent. You have to use the migration script and the procedure described here: https://github.com/OpenCTI-Platform/migration_script_v4.

Let us know if you need any help to use it.

Kind regards,
Samuel

**Comment by marcosepp** [comment]
Thanks! 
I was able to migrate the CTI data, but the migration script didn't migrate the users, roles nor groups unfortunately. Is there a solution how to migrate the users?

**Comment by richard-julien** [comment]
Hi @marcosepp,
There is no solution to migrate the users/groups with the current migration.

**Comment by marcosepp** [comment]
Thanks for the answer. Do you know if there will be a solution for that?

**Comment by richard-julien** [comment]
Hi @marcosepp . There is no out of the box solution. If its mandatory for you we need to develop a specific migration script. Can you recreate your users by hand or you really need a migration script?
