### ISSUE TITLE
No port 8080 opens

### ISSUE THREAD

**Issue by rocheston** [OpenCTI-Platform/docker#22]
I followed your advice exactly. Still no go. Please suggest. 

OPENCTI_ADMIN_EMAIL=rxx@xx.com
OPENCTI_ADMIN_PASSWORD=xx
OPENCTI_ADMIN_TOKEN=904ccff2-4db2-42ab-81b6-a6820494319d
MINIO_ACCESS_KEY=xx
MINIO_SECRET_KEY=xx
RABBITMQ_DEFAULT_USER=xx
RABBITMQ_DEFAULT_PASS=xx
CONNECTOR_HISTORY_ID=904ccff2-4db2-42ab-81b6-a6820494319d
CONNECTOR_EXPORT_FILE_STIX_ID=904ccff2-4db2-42ab-81b6-a6820494319d
CONNECTOR_EXPORT_FILE_CSV_ID=904ccff2-4db2-42ab-81b6-a6820494319d
CONNECTOR_IMPORT_FILE_STIX_ID=904ccff2-4db2-42ab-81b6-a6820494319d
CONNECTOR_IMPORT_FILE_PDF_OBSERVABLES_ID=904ccff2-4db2-42ab-81b6-a6820494319d

Step 1. 
Download the docker-compose.yml file 

Step 2:
change the .env file

Step 3:
Open terminal and run 
set -o allexport; source .env; set +o allexport

Step 4:
docker-compose --compatibility up

Step 5: 
Wait 30 minutes  +

Step 6:
Go to http://localhost:8080

Step 7:
You are screwed. It does not work.

Step 8:
Repeat the above in fresh Ubuntu with all the dependencies installed.

Step 9:
Screwed again. No port 8080 opens. Port 9000 opens though

-----
Seriously provide some support here.

**Comment by richard-julien** [comment]
First remarks: each connector must have a different UUID.

Now, very difficult to help without any logs.
Please look into the docker logs to see whats going wrong.

**Comment by rocheston** [comment]
You are right. This .env worked. Thank you. The dashboard now loads at http://localhost:8080

OPENCTI_ADMIN_EMAIL=x@x.xx
OPENCTI_ADMIN_PASSWORD=xx
OPENCTI_ADMIN_TOKEN=dc839e92-458b-432b-bf3c-34d4522133d0
MINIO_ACCESS_KEY=xx
MINIO_SECRET_KEY=xx
RABBITMQ_DEFAULT_USER=xx
RABBITMQ_DEFAULT_PASS=xx
CONNECTOR_HISTORY_ID=3bd01869-9cb6-4b45-9db6-7194f2d30730
CONNECTOR_EXPORT_FILE_STIX_ID=d2c32056-8553-4e36-bff2-a6820832b9a8
CONNECTOR_EXPORT_FILE_CSV_ID=033bcead-dc2d-4c82-b19f-36c6ba2f162a
CONNECTOR_IMPORT_FILE_STIX_ID=3e89af21-db8c-4b39-ab87-0533f88fa299
CONNECTOR_IMPORT_FILE_PDF_OBSERVABLES_ID=8c26ab67-b661-45f8-97fe-2792d9921f07

**Comment by richard-julien** [comment]
Perfect.
