### ISSUE TITLE
Inquiry: Upgrading OpenCTI and cleaning-up old version

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/docker#25]
Hi,

This is just an inquiry.
Please advise of what is the best practice when updating OpenCTI docker. Is it safe to remove all docker images & containers when upgrading to a new version of opencti but want to keep all existing data feeds?

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

The best practice to upgrade is just to change the version number in the `docker-compose.yml` file and just type `docker-compose up -d`. This will automatically upgrade and restart the containers.

Kind regards,
Samuel
