### ISSUE TITLE
Docker Compose not working

### ISSUE THREAD

**Issue by nikgreg99** [OpenCTI-Platform/docker#267]
Trying to deploy the OpenCTI platform trought Docker Swarm following the guide make me fail. I cannot connect to web UI, I have only changed the OPENCTI_BASE_URL=http://<ip>:8080 to make it reachable outside and generating an uuid for OPENCTI_ADMIN_TOKEN using $(cat proc/sys/kernel/random/uuid. Otherwise the minio image doens't exist anymore in Docker HUB. Please fix it. My deployment is only local for testing now.

**Comment by SamuelHassine** [comment]
Fixed Docker Hub image. For the base URL, you should put the full URL accessible from outside. This does not have any impact on the listen host
