### ISSUE TITLE
SSL (https) needed for external authentication source

### ISSUE THREAD

**Issue by bLackCat-79** [OpenCTI-Platform/docker#33]
Hi,

We have an opencti instance running on http on port 8080.
Now if I want to use opened provider, it requires that the callback URL has SSL (https).

Do I need to setup an nginx proxy that forwards and upgrades port HTTP 8080 to https port 8081 for example? (we cannot use port 443)

Can I let all my connectors still connect to port 8080?

**Comment by nor3th** [comment]
Hey @bLackCat-79 

You can also just configure OpenCTI to use HTTPS per default for the defined port. Have a look at the 
```
APP__HTTPS_CERT__CA
APP__HTTPS_CERT__KEY
APP__HTTPS_CERT__CRT
```
Docker configuration arguments.
https://www.notion.so/93dd0f2899254b2581553d8b7df362da?v=979adbb6cb8b4e58aeef7c3bfb4c4624

Regards,

**Comment by nor3th** [comment]
Closing this due inactivity
