### ISSUE TITLE
docker_opencti_1 error & restart loop

### ISSUE THREAD

**Issue by xme** [OpenCTI-Platform/docker#41]
I just upgraded my environment to the latest version of the docker containers. Now, I can't start the OpenCTI container...
The error I see in logs is:

```
opencti_1                     | Error: getaddrinfo EAI_AGAIN  minio
opencti_1                     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
```
If I connect quickly on the container, I can resolve/ping the host 'minio'. The container 'minio' is up'n'running too.
Any idea?

**Comment by xme** [comment]
```
root@opencti:/opt/opencti/docker# docker exec -it docker_opencti_1 sh
/opt/opencti # ping minio
PING minio (172.23.0.5): 56 data bytes
64 bytes from 172.23.0.5: seq=0 ttl=64 time=0.323 ms
64 bytes from 172.23.0.5: seq=1 ttl=64 time=0.155 ms
64 bytes from 172.23.0.5: seq=2 ttl=64 time=0.155 ms
```
Then the container exits and restarts... infinite loop....

**Comment by nor3th** [comment]
Hey @xme 

What do the minio logs say? `docker logs opencti_minio-1`? There was a version upgrade for minio as well two environment variables changed. Are you using the new ones? 
https://github.com/OpenCTI-Platform/docker/commit/3b0e9102f717830045e8ccd2b665184e58716a1a#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

Regards

**Comment by xme** [comment]
Yep, minio looks ok:
```
API: http://172.23.0.9:9000  http://127.0.0.1:9000

Console: http://172.23.0.9:37847 http://127.0.0.1:37847

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (37847), please use --console-address ":PORT" to choose a static port.
```

**Comment by nor3th** [comment]
Hey

Hmm the error doesn't make a lot of sense if you can do a lookup from the same container manually. Could you maybe share your docker config?

> What the difference "_" vs "__"? (it's like that in the docker-compose.yml on the repo)

Since there are field names with a "_" inside opencti config file, the "__" are there to act as separators between the dictionary key and the value or subkey. 
https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/config/default.json

Regards,

**Comment by xme** [comment]
You mean the docker-compose or the docker daemon config (which is the default one on Ubuntu).
The resolution can't be performed by node, this could be the problem?
(I tested with a simple ping)

**Comment by nor3th** [comment]
Hey 

The docker-compose config. Yeah I know, that's weird that node can't resolve the domain, but ping can... 
Maybe it's the log output, but it seems to me that there are 2 spaces 'EAI_AGAIN  minio' between `AGAIN` and `minio`. Any chance you defined the minio hostname as ' minio' by mistake?

Regards

**Comment by xme** [comment]
WTF! That was the issue: a space between the "=" and "minio" :(
2h lost for this... Tx for helping (and your time!)

**Comment by nor3th** [comment]
Great, I am glad I was able to help you with that one :)
