### ISSUE TITLE
Opencti api is not reachable.

### ISSUE THREAD

**Issue by federico-acn** [OpenCTI-Platform/docker#49]
Hi, 
I tried to install the platform using "docker" but i receive this error: "Opencti api is not reachable. waiting for opencti api to start or check your configuration".
The platform is accessible on port 8080 but I cannot use the connectors.
Someone can help me please?

**Comment by nor3th** [comment]
Hey

What's your docker config? Can you please also post the docker logs?

Regards

**Comment by federico-acn** [comment]
Hi, thanks for the reply :).
docker-compose.yml
`version: '3'
services:
  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2021-11-09T03-21-45Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
  opencti:
    image: opencti/platform:5.1.1
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=4040
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "4040:4040"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:5.1.1
    environment:
      - OPENCTI_URL=http://opencti:4040
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
  connector-history:
    image: opencti/connector-history:5.1.1
    environment:
      - OPENCTI_URL=http://opencti:4040
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_HISTORY_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=STREAM
      - CONNECTOR_NAME=History
      - CONNECTOR_SCOPE=history
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:5.1.1
    environment:
      - OPENCTI_URL=http://opencti:4040
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:5.1.1
    environment:
      - OPENCTI_URL=http://opencti:4040
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-txt:
    image: opencti/connector-export-file-txt:5.1.1
    environment:
      - OPENCTI_URL=http://opencti:4040
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_TXT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileTxt
      - CONNECTOR_SCOPE=text/plain
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:5.1.1
    environment:
      - OPENCTI_URL=http://opencti:4040
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-import-document:
    image: opencti/connector-import-document:5.1.1
    environment:
      - OPENCTI_URL=http://opencti:4040
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportDocument
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/pdf,text/plain,text/html
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_ONLY_CONTEXTUAL=false # Only extract data related to an entity (a report, a threat actor, etc.)
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - IMPORT_DOCUMENT_CREATE_INDICATOR=true
    restart: always
    depends_on:
      - opencti
volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:
`
docker logs  opencti/platform:5.1.1
`{"auth":{"email":"SYSTEM"},"category":"AUDIT","level":"info","message":"ROLE_CREATION","resource":{"role":{"capabilities":["KNOWLEDGE"],"default_assignation":true,"description":"Default role associated to all users","name":"Default"}},"timestamp":"2021-12-01T08:22:36.219Z","version":"5.1.1"}
{"auth":{"email":"SYSTEM"},"category":"AUDIT","level":"info","message":"ROLE_CREATION","resource":{"role":{"capabilities":["BYPASS"],"description":"Administrator role that bypass every capabilities","name":"Administrator"}},"timestamp":"2021-12-01T08:22:36.589Z","version":"5.1.1"}
{"auth":{"email":"SYSTEM"},"category":"AUDIT","level":"info","message":"ROLE_CREATION","resource":{"role":{"capabilities":["KNOWLEDGE_KNUPDATE_KNDELETE","KNOWLEDGE_KNUPLOAD","KNOWLEDGE_KNASKIMPORT","KNOWLEDGE_KNGETEXPORT_KNASKEXPORT","KNOWLEDGE_KNENRICHMENT","CONNECTORAPI","BYPASSREFERENCE","MODULES_MODMANAGE","STREAMAPI","SETTINGS_SETMARKINGS","SETTINGS_SETLABELS"],"description":"Connector role that has the recommended capabilities","name":"Connector"}},"timestamp":"2021-12-01T08:22:42.718Z","version":"5.1.1"}
{"auth":{"email":"SYSTEM"},"category":"AUDIT","level":"info","message":"USER_CREATION","resource":{"groups":[],"roles":["Default"],"user":"test@test.it"},"timestamp":"2021-12-01T08:22:44.697Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.10","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:50.300Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.13","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:53.048Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.11","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:54.098Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.7","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:54.754Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.13","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:54.966Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.12","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:55.242Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.8","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:55.900Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.9","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:22:59.031Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:172.18.0.10","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2021-12-01T08:23:50.624Z","version":"5.1.1"}
{"auth":{"email":"test@test.it","ip":"::ffff:37.179.176.239","referer":"http://15.160.156.205:4040/dashboard","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"local"},"timestamp":"2021-12-01T09:45:14.264Z","version":"5.1.1"}
`
docker logs docker_connector-history_1
`INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: e1dea050-d749-46e0-bd0b-2534abb0904f
INFO:root:Starting ping alive thread
INFO:root:Getting logs worker config...
INFO:root:Starting listening stream events (URL: http://opencti:4040/stream?from=0, SSL verify: True)
/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py:208: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.15/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
INFO:elasticsearch:PUT http://elasticsearch:9200/opencti_history/_doc/1638346963030-0 [status:201 request:0.121s]
INFO:elasticsearch:PUT http://elasticsearch:9200/opencti_history/_doc/1638346963182-0 [status:201 request:0.096s]
INFO:elasticsearch:PUT http://elasticsearch:9200/opencti_history/_doc/1638346963435-0 [status:201 request:0.091s]
INFO:elasticsearch:PUT http://elasticsearch:9200/opencti_history/_doc/1638346963535-0 [status:201 request:0.023s]
`

**Comment by nor3th** [comment]
Hey

It seems like everything works as intended in the end. OpenCTI just takes a bit to start and that's why the connector isn't able to establish a connection. In the end however, the connection is successfully established.

```
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 101, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 18, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: e1dea050-d749-46e0-bd0b-2534abb0904f
INFO:root:Starting ping alive thread
INFO:root:Getting logs worker config...
INFO:root:Starting listening stream events (URL: http://opencti:4040/stream?from=0, SSL verify: True)
```

Regards

**Comment by federico-acn** [comment]
but when I try to install an external connector (CVE, MISP, ecc), it always gives me this error:
INFO:root:Listing Threat-Actors with filters null.
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

**Comment by nor3th** [comment]
Hey

Did you add those connectors to the same docker-compose file? If not, you have to add the default opencti network to the connector compose file. Make sure via `docker network ls` that the network name is correct.
```
  restart: always
  networks:
    - opencti-default

networks:
  opencti-default:
    external:
      name: opencti-default
```

Regards

**Comment by federico-acn** [comment]
thanks, without your help i would never have solved :)

**Comment by nor3th** [comment]
I am glad that I was able to help you :)

**Comment by MaciaKing** [comment]
Hi nor3th, I have the same problem that you have solved here. But with these, what do you do?

```
 restart: always
  networks:
    - opencti-default

networks:
  opencti-default:
    external:
      name: opencti-default
```
Do you put this code on docker-compose.yml? Or do you add this configuration on another .yml?

Reguards !
