### ISSUE TITLE
Update docker documentation for running in various environments

### ISSUE THREAD

**Issue by mschreib28** [OpenCTI-Platform/docker#56]
## Use case

Update the existing OpenCTI/docker documentation to include dev/prod environments to include capabilities for easier local development of the front-end as well as default overrides.

## Current Workaround

Manual manipulation of the docker-compose.yml is required to run various settings within docker-compose

## Proposed Solution

Utilize `docker-compose.override.yml` and add documentation on how to run the different `docker-compose.*.yml` versions based on environment needs.

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

Yes.

**Comment by SamuelHassine** [comment]
Docs updated: https://docs.opencti.io/5.8.X/deployment/installation/.
