### ISSUE TITLE
ElasticSearch crash all shard failed

### ISSUE THREAD

**Issue by Clemv95** [OpenCTI-Platform/docker#65]
With fresh new install of opencti via docker, with 14G of ram allocate to Elasticsearch, it keep crashing and restarting with the error "all shards failed"

Here is a log : 

`{"type": "server", "timestamp": "2022-08-03T07:05:20,666Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "docker-cluster", "node.name": "c8e1441fb70c", "message": "path: /opencti_internal_objects*%2Copencti_stix_meta_objects*%2Copencti_stix_domain_objects*%2Copencti_stix_cyber_observables*%2Copencti_inferred_entities*/_search, params: {ignore_throttled=false, index=opencti_internal_objects*,opencti_stix_meta_objects*,opencti_stix_domain_objects*,opencti_stix_cyber_observables*,opencti_inferred_entities*, track_total_hits=true}", "cluster.uuid": "s_2g0qFWR46Al8298dbijA", "node.id": "iUZ6digiQpqSVsCubhetxw" , 
"stacktrace": ["org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:713) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:400) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:745) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:497) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.performPhaseOnShard(AbstractSearchAsyncAction.java:308) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.run(AbstractSearchAsyncAction.java:244) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:454) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.start(AbstractSearchAsyncAction.java:199) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.finishPhase(CanMatchPreFilterSearchPhase.java:406) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.access$1100(CanMatchPreFilterSearchPhase.java:66) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$Round.finishRound(CanMatchPreFilterSearchPhase.java:337) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$Round.onOperationFailed(CanMatchPreFilterSearchPhase.java:323) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$Round.doRun(CanMatchPreFilterSearchPhase.java:266) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.runCoordinatorRewritePhase(CanMatchPreFilterSearchPhase.java:190) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.run(CanMatchPreFilterSearchPhase.java:151) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$1.doRun(CanMatchPreFilterSearchPhase.java:487) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.4.jar:7.17.4]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
"at java.lang.Thread.run(Thread.java:833) [?:?]",
"Caused by: org.elasticsearch.action.NoShardAvailableActionException",`

**Comment by nor3th** [comment]
Hey @Clemv95 
Sorry for the delayed answer, but this looks more like an issue on your side. Either purge the elastic volume and then try again or have a look at the other elastic logs why all shards failed. Maybe no more disk space?
